package com.oyp.openglesdemo

object IMyNativeRendererType {
    const val RENDER_TYPE: String = "RENDER_TYPE"

    const val SAMPLE_TYPE = 100

    const val SAMPLE_TYPE_TRIANGLE: Int = SAMPLE_TYPE
    const val SAMPLE_TYPE_TRIANGLE2: Int = SAMPLE_TYPE + 1
    const val SAMPLE_TYPE_TRIANGLE3: Int = SAMPLE_TYPE + 2
    const val SAMPLE_TYPE_KEY_TRIANGLE_MAP_BUFFERS: Int = SAMPLE_TYPE + 3
    const val SAMPLE_TYPE_KEY_TRIANGLE_VERTEX_ARRAY_OBJECT: Int = SAMPLE_TYPE + 4
    const val SAMPLE_TYPE_KEY_TRIANGLE_VERTEX_BUFFER_OBJECT: Int = SAMPLE_TYPE + 5
    const val SAMPLE_TYPE_KEY_CUBE_SIMPLE_VERTEX_SHADER: Int = SAMPLE_TYPE + 6

}